### ISSUE TITLE
评论邮件提醒报错

### ISSUE THREAD

**Issue by Orange-AFK** [halo-dev/plugin-comment-widget#90]
你好，首先我不太确定这个错误和评论插件是否有关系，麻烦帮我看看；
我在测试评论邮件提醒功能的时候，在文章下留评论可以收到邮件提醒，在自定义页面留下评论，halo的日志报告了一个错误，邮件提醒未能收到，但是后台可以看到已经增加了待审核评论；
在文章下的评论后台审核时会显示属于哪一篇文章，而在自定义页面下的评论对应位置却显示未知
以下是错误代码

ERROR 7 --- [        task-22] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void run.halo.app.content.comment.CommentNotificationReasonPublisher.onNewComment(run.halo.app.event.post.CommentCreatedEvent)

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
	at run.halo.app.content.comment.CommentNotificationReasonPublisher$NewCommentOnPageReasonPublisher.publishReasonBy(CommentNotificationReasonPublisher.java:161) ~[classes/:2.13.0]
	at run.halo.app.content.comment.CommentNotificationReasonPublisher.onNewComment(CommentNotificationReasonPublisher.java:64) ~[classes/:2.13.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113) ~[spring-aop-6.1.4.jar:6.1.4]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

**Comment by ruibaby** [comment]
大概率是主题使用不当，因为评论要确定是哪个地方使用需要具体业务模型的 group、kind、name 来确定的，可以参考文档：https://docs.halo.run/developer-guide/theme/template-tag#halocomment

这个问题应该是主题写死了某些系统不存在的模型或者数据。

**Comment by Orange-AFK** [comment]
> 大概率是主题使用不当，因为评论要确定是哪个地方使用需要具体业务模型的 group、kind、name 来确定的，可以参考文档：https://docs.halo.run/developer-guide/theme/template-tag#halocomment
> 
> 这个问题应该是主题写死了某些系统不存在的模型或者数据。

谢谢解答，我向halo以及主题作者发送一下这个错误报告
